# Generated by Django 5.0 on 2026-04-29 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_remove_facture_client_remove_facture_devis_origine_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='statut',
            field=models.CharField(choices=[('BROUILLON', 'Draft'), ('ENVOYEE', 'Sent'), ('PAYEE', 'Paid'), ('EN_RETARD', 'Overdue')], default='BROUILLON', max_length=20, verbose_name='Statut'),
        ),
    ]
