# Generated by Django 5.0 on 2026-04-29 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_address_delete_adresse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='type',
            field=models.CharField(choices=[('SIEGE', 'Headquarters'), ('FACTURATION', 'Billing'), ('LIVRAISON', 'Delivery')], default='SIEGE', max_length=20, verbose_name="Type d'adresse"),
        ),
    ]
