# Generated by Django 5.0 on 2026-04-29 08:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_rename_historiquedevis_quotehistory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='date_emission',
            field=models.DateField(default=datetime.date.today, verbose_name="Date d'émission"),
        ),
        migrations.AlterField(
            model_name='quote',
            name='statut',
            field=models.CharField(choices=[('BROUILLON', 'Draft'), ('ENVOYE', 'Sent'), ('ACCEPTE', 'Accepted'), ('REFUSE', 'Refused'), ('EXPIRE', 'Expired')], default='BROUILLON', max_length=20, verbose_name='Statut'),
        ),
    ]
